allowBuilds:
    esbuild: true
    msw: true
    unrs-resolver: true
    eslint-plugin-jest-extended@https://codeload.github.com/Aesthermortis/eslint-plugin-jest-extended/tar.gz/0767a292476be78588ba2e3190ee11c3ef7582bf: true
