allowBuilds:
    esbuild: true
    msw: true
    unrs-resolver: true
minimumReleaseAgeExclude:
  - tree-element@0.2.0
peerDependencyRules:
  allowedVersions:
    "@rollup/plugin-babel>@babel/core": "8"
