name: Compressed Size
on: [pull_request]

jobs:
    size-job:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository code
              uses: actions/checkout@v7
            - name: Setup node
              uses: actions/setup-node@v7
              with:
                  node-version: "24"
            - name: Install pnpm
              run: npm install -g pnpm
            - name: Check compressed size
              uses: mbraak/compressed-size-action@master
              with:
                  build-script: production
                  install-script: pnpm install
                  pattern: |
                      ./tree.jquery.js
                      ./lib/**/*.js
                  exclude: "{./lib/**/*.d.js,./lib/playwright/**,./lib/test/**}"
                  compression: "none"
